# Generated by Django 4.2.20 on 2025-07-24 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Atendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(max_length=128)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_item", models.CharField(max_length=200)),
                ("quantidade", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["pedido"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_pedido", models.DateTimeField()),
                ("status_pedido", models.CharField(max_length=50)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_pedido"],
            },
        ),
        migrations.CreateModel(
            name="TicketSuporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_ticket",
                    models.CharField(
                        choices=[
                            ("devolucao", "Devolução"),
                            ("troca", "Troca"),
                            ("reclamacao", "Reclamação"),
                            ("duvida", "Dúvida"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_ticket",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("andamento", "Em Andamento"),
                            ("resolvido", "Resolvido"),
                            ("fechado", "Fechado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao_problema", models.TextField()),
                ("data_abertura", models.DateTimeField(auto_now_add=True)),
                ("data_fechamento", models.DateTimeField(blank=True, null=True)),
                (
                    "atendente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="suporte.atendente",
                    ),
                ),
                (
                    "item_pedido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="suporte.itempedido",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="suporte.pedido",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket de Suporte",
                "verbose_name_plural": "Tickets de Suporte",
                "ordering": ["-data_abertura"],
            },
        ),
        migrations.CreateModel(
            name="MensagemAtendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField()),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suporte.ticketsuporte",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["data_envio"],
            },
        ),
        migrations.AddField(
            model_name="itempedido",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="suporte.pedido"
            ),
        ),
    ]
